### ISSUE TITLE
[Routes] Default route "/" not available or defined

### ISSUE THREAD

**Issue by chuayk** [hzk2021/Full-Stack-Dev-Project-#2]
While its optional, having a default GET route for "/" for each router would make your application more user friendly, in the event of users trying to access directly via URL. We don't want to see "Cannot GET /xxx/xxx/xxx" when we try to access a page we expect to see at the URL even if its not completely accurate. Unless otherwise guess-able by human behavior, we return 404.

For example:
```
http://localhost:5000/admin            -> Redirects to http://localhost:5000/admin/dashboard
http://localhost:5000/admin/inventory  -> Redirects to http://localhost:5000/admin/inventory/dashboard
```

**Comment by hzk2021** [comment]
fixed (I think)
